# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "dev"
    allow:
      - dependency-name: "org.beryx.jlink"
      - dependency-name: "org.testng:testng"
      - dependency-name: "com.opencsv:opencsv"
      - dependency-name: "info.solidsoft.pitest"
      - dependency-name: "org.jgrapht:jgrapht-ext"
      - dependency-name: "org.openjfx.javafxplugin"
      - dependency-name: "org.javatuples:javatuples"
      - dependency-name: "org.jetbrains:annotations"
      - dependency-name: "ch.qos.logback:logback-classic"
      - dependency-name: "org.javamodularity.moduleplugin"
      - dependency-name: "org.pitest:pitest-testng-plugin"
      - dependency-name: "com.github.breadmoirai.github-release"
      - dependency-name: "nl.jqno.equalsverifier:equalsverifier"

    ignore:
      - dependency-name: "com.jfoenix:jfoenix"            # Must stay at 9.0.4
      - dependency-name: "io.github.palexdev:materialfx"  # Must stay at 11.12.0


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    target-branch: "dev"
